name = "shuffler-lean"
version = "0.1.0"
defaultTargets = ["shuffler-lean"]

[[lean_lib]]
name = "Shuffler.Lean"

[[lean_exe]]
name = "shuffler-lean"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.34.0"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "v4.34.0"
