name = "shuffler-lean"
version = "0.1.0"
defaultTargets = ["Shuffler"]

[[lean_lib]]
name = "Shuffler"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.34.0"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "v4.34.0"
